// GENERATED by ml/vas_ml/config.py — do not edit by hand.
// Run `python -m vas_ml.config` in ml/ to regenerate.

export const DSP = Object.freeze({
  sample_rate: 16000,
  clip_seconds: 1.0,
  win_length: 640,
  hop_length: 320,
  n_fft: 1024,
  n_mels: 40,
  fmin: 20.0,
  fmax: 7800.0,
  log_floor: 1e-06,
  feature: "logmel",
  n_mfcc: 13,
  n_samples: 16000,
  n_frames: 49,
  n_bins: 40,
  classes: ["doorbell", "fire_alarm", "baby_cry", "glass_break", "tv_music", "background"],
  alert_classes: ["doorbell", "fire_alarm", "baby_cry", "glass_break"],
  conf_threshold: 0.75,
  smooth_window: 5,
  smooth_hits: 3,
  refractory_s: 8.0,
  infer_hop_s: 0.25,
});
